/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication23;
import javax.swing.JFrame;
import javax.swing.JButton;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author CIT
 */
public class View extends javax.swing.JFrame {
 protected JButton but[];
 protected GridLayout grid;
 protected JLabel lab,lab1,lab2;
 protected JPanel p;
    /**
     * Creates new form View
     */
    public View() {
        super("Tic Tac Toe Game");
        initComponents();
        p=new JPanel();
  but = new JButton[9]; 
  //p.add(lab);
  grid= new GridLayout(3,3,5,5); 
  lab= new JLabel("X");
  lab1= new JLabel("Player: ");
  lab2= new JLabel("X");
  add(lab1);
  add(lab);
  //add(lab2);
  grid.setColumns(3);
  grid.setRows(5);
  setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
  setSize(350,300);
  setLayout(grid);
  //jLabel1.setSize(100,20);
  //BUILD BUTTONS
  for(int loop=0; loop<9; loop++)
  {
   but[loop] = new JButton(); 
   add(but[loop]);
  }   
/*   lab.addMouseMotionListener(new MouseMotionAdapter() {
        public void mouseClick(MouseEvent arg0) {
            resetGame();
        }
    });
  */
  lab.setVisible(true);
  setVisible(true);
  
 }
          
 
 // RESET TO GUI
 public void resetGame()
 {
      Models model = new Models();
      View view= new View();
      Controllers controller = new Controllers(model, view);
  lab.setText("X");
  for(int z=0; z<9; z++)
  {
   but[z].setText("");
   but[z].setEnabled(true);
  }
  this.setVisible(false);
}
 public void changePlayer() {
        String newPlayer = reverseValue(getCurrentPlayerString());
        lab.setText(newPlayer);
    }

    public void winGame() {
       lab.setText(getCurrentPlayerString() + " won!");
        for(JButton knob : this.but) {
            knob.setEnabled(false);
        }
        endGame();
    }

    public String reverseValue(String value) {
        if("X".equals(value)) {
            return "O";
        } else if("O".equals(value)) {
            return "X";
        }
        return null;
    }

    public Value reverseValue(Value value) {
        if(value == Value.X) {
            return Value.O;
        } else if (value == Value.O) {
            return Value.X;
        }
        return null;
    }

    public Value getCurrentPlayerValue() {
         if("X".equals(lab.getText())) {
            return Value.X;
        } else if("O".equals(lab.getText())) {
            return Value.O;
        }
         return null;
    }
   
    public String getCurrentPlayerString() {
         if("X".equals(lab.getText())) {
            return "X";
        } else if("O".equals(lab.getText())) {
            return "O";
        }
         return null;
    }

    void setNoWinner() {
        lab1.setText("Game Drawn");
        lab.setText(null);
    }
    void endGame() {
      lab.setEnabled(true);
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Reset Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetGame();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
